version: '3.7'
services:

  backend:
    image: helios-app:${VERSION:-latest}
    ports:
      - 8080:8080
    depends_on:
      - database
      - admin
    networks:
      backend_network:
        aliases:
          - heliosapp
    environment:
      - logging_level_com_github_mwierzchowski_helios=INFO
      - spring_datasource_url=jdbc:postgresql://heliosdb:5432/helios
      - spring_boot_admin_client_url=http://heliosadmin:1111
      - spring_boot_admin_client_username=admin
      - spring_boot_admin_client_password=${ADMIN_PASSWORD:-admin}
      - spring_mail_host=${MAIL_HOST:-false}
      - spring_mail_username=${MAIL_USER:-}
      - spring_mail_password=${MAIL_PASSWORD:-}
      - helios_mail_recipient=${MAIL_RECIPIENT:-}
      - helios_owm_api-key=${OWM_API_KEY:-false}

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      backend_network:
        aliases:
          - heliosdb
    volumes:
      - database_data=/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-helios}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-helios}

  admin:
    image: slydeveloper/spring-boot-admin:latest
    ports:
      - 8090:1111
    networks:
      backend_network:
        aliases:
          - heliosadmin
    environment:
      - spring_boot_admin_ui_title=Helios Admin
      - spring_boot_admin_security_enabled=true
      - spring_security_user_name=admin
      - spring_security_user_password=${ADMIN_PASSWORD:-admin}

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 80:8080
    depends_on:
      - backend
    networks:
      - backend_network
    environment:
      - BASE_URL=/swagger
      - URL=http://localhost:8080/api/openapi.json

volumes:
  database_data:

networks:
  backend_network: