# Application info
info.app:
  name: Helios
  description: Sun blinds controller

# Jersey
spring.jersey:
    application-path: /api

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

# Logging levels
logging.level:
  root: WARN
  com.github.mwierzchowski.helios: INFO

# Persistence
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/helios'
    username: 'helios'
    password: 'helios'
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase.change-log: classpath:liquibase-changelog.sql

decorator.datasource.p6spy:
  enable-logging: false
  log-format: '(connection %(connectionId) - %(category)) %(sql)'

# Mail configuration, to enable please provide host (e.g. smtp.gmail.com)
spring.mail:
  port: 587
  username: 'REPLACE_WITH_YOUR_USER'
  password: 'REPLACE_WITH_YOUR_USER_PASSWORD'
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

# Fault tolerance
resilience4j.retry.instances:
  owm:
    maxRetryAttempts: 6
    waitDuration: 1s
    enableExponentialBackoff: true
    exponentialBackoffMultiplier: 2
    retryExceptions:
    - java.lang.Exception
  sun-api-cache:
    maxRetryAttempts: 240
    waitDuration: 15s
    enableExponentialBackoff: false
    retryExceptions:
      - java.lang.Exception
  sun-api:
    maxRetryAttempts: 6
    waitDuration: 1s
    enableExponentialBackoff: true
    exponentialBackoffMultiplier: 2
    retryExceptions:
      - java.lang.Exception