name: CI
on:  push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Java 13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13

    - name: Set up Gradle Wrapper
      run: chmod +x gradlew

    - name: Set up dependencies cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Assemble
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test jacocoTestReport

    - name: Check if test summary is available
      id: check_test_summary
      if: always()
      uses: andstor/file-existence-action@v1
      with:
        files: "/home/runner/work/helios/helios/build/reports/tests/test"

    - name: Export test summary
      if: steps.check_test_summary.outputs.files_exists == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: Test Summary
        path: /home/runner/work/helios/helios/build/reports/tests/test

    - name: Quality scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube -Dsonar.branch.name=$GITHUB_REF_NAME
