name: CI
on: push
env:
  TEST_SUMMARY: /home/runner/work/helios/helios/build/reports/tests/test

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout tags
      run: git fetch --prune --unshallow

    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13

    - name: Set up Gradle Wrapper
      run: chmod +x gradlew

    - name: Set up dependencies cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*')}}
        restore-keys: |
          ${{runner.os}}-gradle-

    - name: Set up Semantic Versioning
      run: echo "::set-env name=VERSION::$(git describe --tags --always --first-parent --dirty)"

    - name: Assemble application
      run: ./gradlew assemble

    - name: Assemble image
      run: docker build -t helios:latest -t helios:$VERSION .

    - name: Deploy test environment
      env:
        OWM_API_KEY: ${{secrets.OWM_API_KEY}}
        MAIL_HOST: smtp.gmail.com
        MAIL_USER: ${{secrets.TEST_MAIL_USER}}
        MAIL_PASSWORD: ${{secrets.TEST_MAIL_PASS}}
        MAIL_RECIPIENT: ${{secrets.TEST_MAIL_USER}}@gmail.com
      run: docker-compose up -d

    - name: Test E2E
      run: ./gradlew testE2E

    - name: Quality scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      run: ./gradlew sonarqube -Dsonar.branch.name=$GITHUB_REF_NAME

    - name: Check if test summary is available
      id: check_test_summary
      if: always()
      uses: andstor/file-existence-action@v1
      with:
        files: ${{env.TEST_SUMMARY}}

    - name: Publish test summary
      if: steps.check_test_summary.outputs.files_exists == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: Test Summary
        path: ${{env.TEST_SUMMARY}}